"""python_versions mirror_sources reshape envs

Revision ID: 13deac75e91b
Revises: 4a8f0f3b711f
Create Date: 2026-05-18 15:03:13.779349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13deac75e91b'
down_revision: Union[str, Sequence[str], None] = '4a8f0f3b711f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_sources',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('python_versions',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tarball_url', sa.String(length=512), nullable=True),
    sa.Column('install_path', sa.String(length=512), nullable=True),
    sa.Column('build_log_path', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_versions_version'), 'python_versions', ['version'], unique=True)
    # Idempotently ensure environments.name exists. Older dev databases were
    # patched manually; fresh installs need the column before the UNIQUE below.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'environments' AND column_name = 'name'
            ) THEN
                ALTER TABLE environments
                ADD COLUMN name VARCHAR(128) NOT NULL DEFAULT 'default';
            END IF;
        END
        $$;
        """
    )
    op.add_column('environments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('environments', sa.Column('node_id', sa.UUID(), nullable=True))
    op.add_column('environments', sa.Column('python_version_id', sa.UUID(), nullable=True))
    op.add_column('environments', sa.Column('mirror_id', sa.UUID(), nullable=True))
    op.add_column('environments', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('environments', sa.Column('install_log_path', sa.String(length=512), nullable=True))
    op.add_column('environments', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('environments', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('environments', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.alter_column('environments', 'venv_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_unique_constraint(None, 'environments', ['name'])
    op.create_foreign_key(None, 'environments', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'environments', 'python_versions', ['python_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'environments', 'workers', ['node_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'environments', 'mirror_sources', ['mirror_id'], ['id'], ondelete='SET NULL')
    op.drop_column('environments', 'python_version')
    op.drop_column('environments', 'requirements_hash')
    op.drop_column('environments', 'packages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('packages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('environments', sa.Column('requirements_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('environments', sa.Column('python_version', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_constraint(None, 'environments', type_='unique')
    op.alter_column('environments', 'venv_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('environments', 'owner_id')
    op.drop_column('environments', 'error_msg')
    op.drop_column('environments', 'tags')
    op.drop_column('environments', 'install_log_path')
    op.drop_column('environments', 'requirements')
    op.drop_column('environments', 'mirror_id')
    op.drop_column('environments', 'python_version_id')
    op.drop_column('environments', 'node_id')
    op.drop_column('environments', 'description')
    op.drop_index(op.f('ix_python_versions_version'), table_name='python_versions')
    op.drop_table('python_versions')
    op.drop_table('mirror_sources')
    # ### end Alembic commands ###
