"""tasks task_runs deps reshape

Revision ID: 4a8f0f3b711f
Revises: f6b15b658e11
Create Date: 2026-05-18 14:26:53.741815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a8f0f3b711f'
down_revision: Union[str, Sequence[str], None] = 'f6b15b658e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('upstream_task_id', sa.UUID(), nullable=False),
    sa.Column('on_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'upstream_task_id'),
    sa.UniqueConstraint('task_id', 'upstream_task_id', name='uq_task_dep')
    )
    op.create_table('task_runs',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('retry_no', sa.Integer(), nullable=False),
    sa.Column('log_file_path', sa.String(length=512), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_task_id'), 'task_runs', ['task_id'], unique=False)
    op.drop_constraint(op.f('tasks_schedule_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.add_column('tasks', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('env_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('command', sa.Text(), nullable=False))
    op.add_column('tasks', sa.Column('schedule_type', sa.String(length=16), nullable=False))
    op.add_column('tasks', sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('node_strategy', sa.String(length=16), nullable=False))
    op.add_column('tasks', sa.Column('node_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('max_concurrent', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('concurrent_policy', sa.String(length=16), nullable=False))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('timeout_sec', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['name'])
    op.create_foreign_key(None, 'tasks', 'environments', ['env_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'version_id')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'finished_at')
    op.drop_column('tasks', 'trigger_type')
    op.drop_column('tasks', 'worker_id')
    op.drop_column('tasks', 'exit_code')
    op.drop_column('tasks', 'schedule_id')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'error_message')
    op.drop_column('tasks', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('trigger_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_schedule_id_fkey'), 'tasks', 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'owner_id')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'is_active')
    op.drop_column('tasks', 'timeout_sec')
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'concurrent_policy')
    op.drop_column('tasks', 'max_concurrent')
    op.drop_column('tasks', 'node_target')
    op.drop_column('tasks', 'node_strategy')
    op.drop_column('tasks', 'schedule_config')
    op.drop_column('tasks', 'schedule_type')
    op.drop_column('tasks', 'command')
    op.drop_column('tasks', 'env_id')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'name')
    op.create_table('task_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_logs_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_logs_pkey'))
    )
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_table('schedules',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('cron_expr', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('run_at', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('depends_on', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('schedules_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.drop_index(op.f('ix_task_runs_task_id'), table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
