"""worker_metrics timeseries

Revision ID: 8ed2629ebff4
Revises: 13deac75e91b
Create Date: 2026-05-18 15:22:10.733901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed2629ebff4'
down_revision: Union[str, Sequence[str], None] = '13deac75e91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=False),
    sa.Column('mem_pct', sa.Float(), nullable=False),
    sa.Column('disk_pct', sa.Float(), nullable=False),
    sa.Column('net_in_bps', sa.BigInteger(), nullable=False),
    sa.Column('net_out_bps', sa.BigInteger(), nullable=False),
    sa.Column('running_tasks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_metrics_ts'), 'worker_metrics', ['ts'], unique=False)
    op.create_index(op.f('ix_worker_metrics_worker_id'), 'worker_metrics', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_metrics_worker_id'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_ts'), table_name='worker_metrics')
    op.drop_table('worker_metrics')
    # ### end Alembic commands ###
