"""project reshape git_repos files distributions

Revision ID: f6b15b658e11
Revises: 256bc09b252e
Create Date: 2026-05-18 13:53:03.435346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b15b658e11'
down_revision: Union[str, Sequence[str], None] = '256bc09b252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_repos',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('project_distributions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['workers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'node_id', name='uq_proj_dist')
    )
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.drop_table('project_versions')
    op.add_column('projects', sa.Column('source_type', sa.String(length=8), nullable=False))
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('default_node_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('default_env_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('current_hash', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('fk_projects_environment_id'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'environments', ['default_env_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'workers', ['default_node_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'python_version')
    op.drop_column('projects', 'git_username')
    op.drop_column('projects', 'entry_file')
    op.drop_column('projects', 'max_concurrency')
    op.drop_column('projects', 'git_branch')
    op.drop_column('projects', 'deploy_type')
    op.drop_column('projects', 'environment_id')
    op.drop_column('projects', 'git_token')
    op.drop_column('projects', 'worker_id')
    op.drop_column('projects', 'git_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('git_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('git_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('environment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deploy_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('git_branch', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('max_concurrency', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('entry_file', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('git_username', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('python_version', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_environment_id'), 'projects', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'current_hash')
    op.drop_column('projects', 'default_env_id')
    op.drop_column('projects', 'default_node_id')
    op.drop_column('projects', 'owner_id')
    op.drop_column('projects', 'source_type')
    op.create_table('project_versions',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('deploy_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_versions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_versions_pkey'))
    )
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_table('project_distributions')
    op.drop_table('git_repos')
    # ### end Alembic commands ###
